screen = None
event_manager = None
input_manager = None
image_manager = None
deck_series_manager = None
card_prints_manager = None
fonts = {}
image_dir = "data/img/"
card_image_dir = image_dir + "cards/"